"""Structured `page_state` representation of a landing page.

`page_state` is the single source of truth produced by the LLM: a JSON
document describing the sections of the page. The HTML is always derived
from it through the existing assembler, never generated by the LLM.
"""

from app.services.ollama_service import generate_fallback_content

PAGE_STATE_VERSION = 1

# section id -> {prop name: "text" | "list"}
SECTION_SCHEMA: dict[str, dict[str, str]] = {
    "hero": {"title": "text", "subtitle": "text", "cta_text": "text"},
    "problem_solution": {
        "problem_title": "text",
        "problem_text": "text",
        "solution_title": "text",
        "solution_text": "text",
    },
    "program": {"intro": "text", "skills": "list"},
    "social_proof": {"headline": "text", "highlight_stat": "text"},
    "pricing": {
        "headline": "text",
        "value_proposition": "text",
        "cta_text": "text",
        "guarantee": "text",
    },
    "instructor": {"headline": "text", "bio_highlight": "text"},
}

SECTION_ORDER = list(SECTION_SCHEMA)


def _extract_sections(raw: dict) -> dict[str, dict]:
    """Accept either a page_state document or a flat `{section: {props}}` dict."""
    if not isinstance(raw, dict):
        return {}

    sections = raw.get("sections")
    if isinstance(sections, list):
        extracted = {}
        for section in sections:
            if not isinstance(section, dict):
                continue
            section_id = section.get("id") or section.get("type")
            props = section.get("props")
            if section_id in SECTION_SCHEMA and isinstance(props, dict):
                extracted[section_id] = {"props": props, "visible": section.get("visible", True)}
        return extracted
    if isinstance(sections, dict):
        raw = sections

    return {
        section_id: {"props": props, "visible": True}
        for section_id, props in raw.items()
        if section_id in SECTION_SCHEMA and isinstance(props, dict)
    }


def _clean_props(section_id: str, props: dict, defaults: dict) -> dict:
    cleaned = {}
    for name, kind in SECTION_SCHEMA[section_id].items():
        value = props.get(name)
        if kind == "list":
            items = [str(item).strip() for item in value if str(item).strip()] if isinstance(value, list) else []
            cleaned[name] = items or list(defaults.get(name, []))
        else:
            text = str(value).strip() if isinstance(value, (str, int, float)) else ""
            cleaned[name] = text or str(defaults.get(name, ""))
    return cleaned


def build_page_state(campaign: dict, raw_content: dict) -> dict:
    """Normalize whatever the LLM returned into a complete page_state document."""
    fallback = generate_fallback_content(campaign)
    extracted = _extract_sections(raw_content)

    sections = []
    for section_id in SECTION_ORDER:
        entry = extracted.get(section_id, {})
        sections.append(
            {
                "id": section_id,
                "type": section_id,
                "visible": bool(entry.get("visible", True)),
                "props": _clean_props(
                    section_id, entry.get("props", {}), fallback.get(section_id, {})
                ),
            }
        )

    branding = campaign.get("branding", {})
    return {
        "version": PAGE_STATE_VERSION,
        "meta": {
            "formation_name": campaign.get("formation", {}).get("name", ""),
            "language": "fr",
        },
        "theme": {
            "primary_color": branding.get("primary_color", "#2563eb"),
            "secondary_color": branding.get("secondary_color", "#1e40af"),
            "style": branding.get("style", "Moderne"),
            "tone": branding.get("tone", "Professionnel"),
        },
        "sections": sections,
    }


def apply_updates(
    page_state: dict, updates: dict, visibility: dict | None = None
) -> tuple[dict, list[str]]:
    """Apply `{section_id: {prop: value}}` edits to a page_state.

    Unknown sections/props and empty values are ignored, so a bad LLM answer can
    never corrupt the page. Returns the new page_state and the changed props
    as `"section.prop"` / `"section.visible"` labels.
    """
    updates = updates if isinstance(updates, dict) else {}
    visibility = visibility if isinstance(visibility, dict) else {}
    changed: list[str] = []
    sections = []

    for section in page_state.get("sections", []):
        section_id = section.get("id")
        props = dict(section.get("props", {}))
        visible = bool(section.get("visible", True))

        for name, value in (updates.get(section_id) or {}).items():
            if name not in SECTION_SCHEMA.get(section_id, {}):
                continue
            cleaned = _clean_props(section_id, {name: value}, props)[name]
            if cleaned and cleaned != props.get(name):
                props[name] = cleaned
                changed.append(f"{section_id}.{name}")

        if section_id in visibility and isinstance(visibility[section_id], bool):
            if visibility[section_id] != visible:
                visible = visibility[section_id]
                changed.append(f"{section_id}.visible")

        sections.append({**section, "props": props, "visible": visible})

    return {**page_state, "sections": sections}, changed


def page_state_to_content(page_state: dict) -> dict:
    """Flatten a page_state into the `ai_content` dict expected by the assembler."""
    return {
        section["id"]: section["props"]
        for section in page_state.get("sections", [])
        if isinstance(section, dict) and section.get("id") and section.get("visible", True)
    }
