"""Convert a generated HTML landing page into a self-contained React component."""

from __future__ import annotations

import json
import re

from bs4 import BeautifulSoup


def _component_name(formation_name: str) -> str:
    words = re.findall(r"[A-Za-z0-9]+", formation_name)
    name = "".join(word[:1].upper() + word[1:] for word in words)
    return f"{name or 'LandingPage'}LandingPage"


def build_react_component(html: str, formation_name: str) -> str:
    """Return a downloadable .tsx component without tracking or executable scripts."""
    soup = BeautifulSoup(html, "html.parser")
    for tag in soup.find_all(["script", "noscript"]):
        tag.decompose()

    styles = "\n\n".join(style.get_text() for style in soup.find_all("style"))
    for style in soup.find_all("style"):
        style.decompose()

    markup = soup.body.decode_contents() if soup.body else str(soup)
    component_name = _component_name(formation_name)
    return f'''import type {{ CSSProperties }} from "react";

/** Generated by AI Crafters Landing Builder. */
export interface {component_name}Props {{
  className?: string;
  style?: CSSProperties;
}}

const landingPageStyles = {json.dumps(styles, ensure_ascii=False)};
const landingPageMarkup = {json.dumps(markup, ensure_ascii=False)};

export default function {component_name}({{ className, style }}: {component_name}Props) {{
  return (
    <div className={{className}} style={{style}}>
      <style>{{landingPageStyles}}</style>
      <div dangerouslySetInnerHTML={{{{ __html: landingPageMarkup }}}} />
    </div>
  );
}}
'''
